### ISSUE TITLE
[Meta] Fix Various Search Bugs

### ISSUE THREAD

**Issue by bhajneet** [shabados/presenter#211]
Splitting the various search bugs into their own issues. _Originally posted by @bhajneet in https://github.com/ShabadOS/desktop/issues/103#issuecomment-533840122_

- [x] Change shift-f hotkey in search bar / input box #213 
- [x] Do not change insertion point of search bar / input box query with up and down keys #215
- [x] Unify accent insertion/deletion in search bar #166
- [x] Wrongly formatted search results when using wildcard #217
- [ ] Fix vishraam issue in search #169
- [x] Fix incorrect highlighting of full word search results #170
- [x] Do not focus / highlight search bar / input box when using up on first entry or down on last entry #214
- [x] Segregate home / end hotkeys in search #168
- [x] Fix tab key in search #212
