### ISSUE TITLE
Implement features for Basics of Sikhi's video editor team

### ISSUE THREAD

**Issue by preetcharan** [shabados/presenter#85]
_This section added by @bhajneet_

- [x] Add hotkeys to allow BoS users to customize the separate field copying into single hotkeys #176 
- [ ] Copy not working from search #511
- [x] Format strings for citations #513
- [x] Ability to remove lines and page numbers from translits #508
- [x] Line numbers are showing up in copying of lines when line numbers are set to hidden #587
- [x] Copy doesn't work on first hotkey/stroke https://github.com/ShabadOS/desktop/issues/437
- [ ] Properly show last line activated of shabad in History activity #390
- [ ] Add group lines by pauri/section for presenter/overlay https://github.com/ShabadOS/desktop/issues/442
- [ ] Add non-activated line selector (pseudo / semi select lines which are activated with enter or mouse click) #237
- [x] Add option for metadata in search results #225 
- [x] Add copy for selected search/nav item which allows separate field copying #188
- [x] Add hindi/urdu transliteration #198 
- [x] Add basics of sikhi transliteration key https://github.com/ShabadOS/gurmukhi-utils/issues/102
---

For BoS Video Editor's Team, the Shabad OS team made a mac (and pc) version of Shabad OS called "Shabad OS - May 18, 2018". I am requesting a mac version of the BoS modified ShabadOS app to include Hindi transliterations. 

In this version the main differences to the standard version are that in the search you can see the author, ang number (of the pangti) and it is formatted to the BoS Brand Guidelines. E.g. `Guru Nanak Dev Ji - SGGS Ji - Ang 1`

From this you are able to copy and paste different elements of the pangti using shortcuts:

cmd+g = copy gurmukhi
cmd+t = copy transliteration
cmd+e = copy english translation
cmd+a = copy author

I would like to be able to copy the hindi transliteration too using a hotkey. cmd+h would be useful. 

If you are going to be working from the version I have been given, then there are some other updates I have been saving to give to the team if I can give them too. Also if there any database updates, this is switched off on my version so that would be appreciated too.

This is the version I'm using: https://drive.google.com/open?id=1dcn-UGf4Hjgjc_aN_w1BlS2qEA73yoVx
